S = [
  "650 Stillwater Ave, Bangor",
  "2435 Lafayette St, Santa Clara",
  "Bennington VT",
  "Rhode Island Ave Washington DC",
  "Ellicott City MD",
  "Catonsville MD",
  "W Little Rock AR",
  "Conway AR",
  "Ellsworth ME",
  "West Mifflin PA",
  "Ross Township PA",
  "Wilkins PA",
  "Sioux Falls",
  "Iron Mountain MI",
  "Cicero IL",
  "Evanston IL",
  "Las Cruces NM",
  "W El Paso TX",
  "East El Paso TX",
  "4640 Roosevelt Blvd PA"
  ]